### ISSUE TITLE
Cannot Connect User Profile in Acumatica

### ISSUE THREAD

**Issue by dcoll22** [Acumatica/Acumatica-Smartsheet#4]
When I try to connect my Acumatica user to my Smartsheet user account, it is giving me a failure as if there is a missing link in Acumatica customization project. Is there something I may have missed in setting this integration up?

Acumatica Version - 20.101.0032

![image](https://user-images.githubusercontent.com/66973410/84703183-cdd28c80-af25-11ea-97dd-205a7d669ecc.png)

**Comment by dcoll22** [comment]
Note: It correctly brings up the authorize page and the error occurs after clicking "allow"

![image](https://user-images.githubusercontent.com/66973410/84703733-c069d200-af26-11ea-8b0f-0da8f16bb8da.png)

**Comment by dcoll22** [comment]
After further review and troubleshooting, it looks like the integration uses PMSubTasks but these are not included in Acumatica 2020 R1 from my brief attempt to look into it. I believe this detail is now being found with Cost Codes instead of subtasks. I may be entirely missing something here but thought I would share my findings.

**Comment by DhirenChhapgar** [comment]
@dcoll22 , 
#1. About token issue, are you using e-mail as username in Acumatica ? If so, there's a known issue at present with this integration. Try to use acumatica username which is not e-mail address until this issue is fixed. 
#2. About **PMSubTasks** and **CostCode** -
Yes, integration uses **PMSubTasks** and that is part of SmartSheet integration not in core Acumatica. **PMSubTasks** is custom table. Cost codes has not been utilized in SmartSheet integration. Please submit an idea and use case at https://feedback.acumatica.com/.

**Comment by kulvirTAC** [comment]
@dcoll22 Is there a workaround here to get this integration working for 2020 R1 or higher?  I am experiencing the same issue for a 2020R2 environment.

**Comment by AlinPara** [comment]
I have the same issue on Acumatica 2020R2 as @dcoll22 .
@DhirenChhapgar the username in Acumatica instance is not the e-mail address.
I tried with the last version of the package (v2).

**Comment by AlinPara** [comment]
For 2020R2 the problem was solved after publishing the version of the package.

**Comment by kulvirTAC** [comment]
Confirmed, we have this working with 2020R2 as well using build 20.201.0051.

**Comment by famadoz** [comment]
@dcoll22 would you please indicate if this issue is still occurring?

@kulvirTAC @AlinPara FYI - a new version for 2021R1 is now available in the repository as well.
