### ISSUE TITLE
Unable to synchronize projects; received error when trying to sync to Smartsheets

### ISSUE THREAD

**Issue by ksherm65aktion** [Acumatica/Acumatica-Smartsheet#6]
Hello,
Issues in Version 2020R2 build 202.0043
I have populated tasks with dates and durations.
On project tasks, there is no box to enable subtask dependencies as there is in the project template field.  Any help on the error message below?
Thank you,
Kathy

Error: | End Dates on dependency-enabled sheets cannot be created/updated. Please update either the Duration or Start Date column. | Send
-- | -- | --
  | Raised At: 11/30/2020 12:59:11 PM | Screen: PM.30.10.00 |   |  
Details:11/30/2020 12:59:11 PM Error:End Dates on dependency-enabled sheets cannot be created/updated. Please update either the Duration or Start Date column.   at SmartSheetIntegration.ProjectEntryExt.CreateUpdateGanttProject(ProjectEntry projectEntryGraph, PMProject pmProjectRow, SmartsheetClient smartsheetClient, Boolean isMassProcess) in C:\Project\Acumatica\SkyAcu\App_Data\Projects\SmartsheetIntegrationV2\PM\ProjectEntryExt.cs:line 376   at SmartSheetIntegration.ProjectEntryExt.<>c__DisplayClass7_0.b__0() in C:\Project\Acumatica\SkyAcu\App_Data\Projects\SmartsheetIntegrationV2\PM\ProjectEntryExt.cs:line 132   at PX.Data.PXLongOperation.<>c__DisplayClass17_0.b__0()

**Comment by sdimeglio** [comment]
Hello,
I have the same issue, were you able to resolve the issue?
Thanks
Sebastien

**Comment by Naveen1220211106** [comment]
Hello, I also getting the same issue :(  Can anyone help me with this?
![image](https://user-images.githubusercontent.com/83211499/116056031-f4f7ff80-a69a-11eb-849a-b80a379abe98.png)

**Comment by famadoz** [comment]
@ksherm65aktion @sdimeglio @Naveen1220211106 
It is likely that your current configuration of the Smartsheet Mapping in Acumatica is trying to assign a field to a non-assignable-via-API field in Smartsheet.

There are some templates in Smartsheet that allow the modification of the _Duration_ - via API - but not the modification of the _End Date_.
![image](https://user-images.githubusercontent.com/18151942/117228665-1c5b7480-addf-11eb-97fb-d66caf41a18d.png)

That is the reason why the new column "Duration" had to get included in the **Tasks** grid of the **Projects** page.

I have created a sample mapping for a scenario similar to yours. Please refer to the following images:
![image](https://user-images.githubusercontent.com/18151942/117228222-452f3a00-adde-11eb-8982-b4573b832403.png)

Notice the use of the _Duration_ instead of the _End Date_ in the mapping.

This is the result in Smartsheet:
![image](https://user-images.githubusercontent.com/18151942/117228261-5b3cfa80-adde-11eb-8ed7-1625b76d4fda.png)


Please try this change and let me know the outcome.

**Comment by noahriley** [comment]
Thank you! Leaving the end date out allowed for sync.

**Comment by famadoz** [comment]
Great! Thanks for the confirmation @noahriley
